# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brochure Ufolep
email: brenon.alexis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Une version compressée de la brochure de gymnastique artistique de l'Ufolep
baseurl: "/ufolep-tools" # the subpath of your site, e.g. /blog
url: "https://alexisbrenon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: AlexisBRENON
repository: AlexisBRENON/ufolep-tools

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_bootstrap.sh
